Problem - 1: Array Creation

In [7]:
import numpy as np
# 1. Initialize an empty array with size 2*2
empty_array = np.empty((2, 2))
print("Empty Array (2*2):\n", empty_array)

# 2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("\n All ones (4*2): \n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
fill_value = 3 #example fill value.
shape = (3,3)
filled_array = np.full(shape, fill_value)
print("\n Array filled Array (3*3): \n", filled_array)

# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
given_array = np.array([[1,2], [3,4]])
zeros_like_array = np.zeros_like(given_array)
print("\n array of zeros with same shape and type as a given array : \n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_like_array = np.ones_like(given_array)
print("\n array of ones with same shape and type as a given array : \n", ones_like_array)

# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("\n Numpy array from list: \n", numpy_array)


Empty Array (2*2):
 [[0. 0.]
 [0. 0.]]

 All ones (4*2): 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 Array filled Array (3*3): 
 [[3 3 3]
 [3 3 3]
 [3 3 3]]

 array of zeros with same shape and type as a given array : 
 [[0 0]
 [0 0]]

 array of ones with same shape and type as a given array : 
 [[1 1]
 [1 1]]

 Numpy array from list: 
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [29]:
import numpy as np
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array_10_to_49 = np.arange(10,50)
print("Array with value ranging from 10 to 49 :\n", array_10_to_49)

# 2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
matrix = np.arange(9).reshape(3,3)
print("\n 3*3 matrix with values ranging from 0 to 8 is :\n ",matrix)

# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3,3)
print("\n 3*3 identity matrix is : \n",identity_matrix)
# 4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n Random array of size 30 is : \n",random_array)
print("\n the mean of the array is : \n",mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values.
random_array_10 = np.random.random(10)
min_value = random_array_10.min()
max_value = random_array_10.max()
print("\n Random array of size 10*10 is : \n",random_array_10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1.
Zero_array = np.zeros(10)
Zero_array[4] = 1
print("\n Zero array of size 10 is : \n",Zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0].
array = np.array([1,2,0,0,4,0])
reversed_array = array[::-1]
print("\n Reversed array is : \n",reversed_array)

# 8. Create a 2d array with 1 on border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n 2d array with 1 on border and 0 inside is : \n",border_array)

# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)

Array with value ranging from 10 to 49 :
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 3*3 matrix with values ranging from 0 to 8 is :
  [[0 1 2]
 [3 4 5]
 [6 7 8]]

 3*3 identity matrix is : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random array of size 30 is : 
 [0.30659969 0.48364332 0.44099243 0.03805778 0.10176027 0.28732327
 0.22652966 0.46855294 0.67364498 0.49140625 0.57561051 0.29768226
 0.65145879 0.937299   0.5152391  0.29537663 0.07856759 0.51964232
 0.42527769 0.14791428 0.92495137 0.06452608 0.33620809 0.08966642
 0.81600447 0.50309616 0.30283435 0.85291957 0.08096525 0.2497921 ]

 the mean of the array is : 
 0.40611808677804223

 Random array of size 10*10 is : 
 [0.30175541 0.98165593 0.35596178 0.85387007 0.77242122 0.59326163
 0.57247797 0.22967091 0.67163056 0.55891723]
Minimum Value: 0.2296709102757235
Maximum Value: 0.9816559257117028

 Zero array of size 10 is : 
 [0. 0. 0. 0. 1. 0. 0.

Problem - 3: Array Operations:

In [37]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

# 1. Add the two array.
Add_array = x + y
print("The addition between two are is :",Add_array)

# 2. Subtract the two array.
Sub_array = x - y
print("The subtraction between two are is :",Sub_array)

# 3. Multiply the array with any integers of your choice.
Input = int(input("Enter the number : "))
Mul_array = x * Input
print("The multiplication between two are is :",Mul_array)

# 4. Find the square of each element of the array.
Square_array = np.square(x)
print("The square of each element of the array is :",Square_array)

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)
print("The dot product between v and w is :",dot_vw)
print("The dot product between x and v is :",dot_xv)
print("The dot product between x and y is :",dot_xy)

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
Concatenate_xy = np.concatenate((x,y),axis = 0)
Concatenate_vw = np.vstack((v,w)).T
print("Concatenate x and y along row is :",Concatenate_xy)
print("Concatenate v and w along column is :",Concatenate_vw)
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
  Concatenate_xv = np.concatenate((x,v),axis = 0)
  print("Concatenate x and v is :",Concatenate_xv)
except ValueError as e:
  print("\nError when concatenating x and v:\n", e)
  print("Explanation: x is a 2D array of shape (2, 2), while v is a 1D array of shape (2,). "
      "To concatenate, both arrays must have the same dimensions along the axis of concatenation.")


The addition between two are is : [[ 6  8]
 [10 13]]
The subtraction between two are is : [[-4 -4]
 [-4 -3]]
Enter the number : 4
The multiplication between two are is : [[ 4  8]
 [12 20]]
The square of each element of the array is : [[ 1  4]
 [ 9 25]]
The dot product between v and w is : 219
The dot product between x and v is : [29 77]
The dot product between x and y is : [[19 22]
 [50 58]]
Concatenate x and y along row is : [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column is : [[ 9 11]
 [10 12]]

Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array of shape (2, 2), while v is a 1D array of shape (2,). To concatenate, both arrays must have the same dimensions along the axis of concatenation.


Problem - 4: Matrix Operations:


In [46]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A^−1 = I.
A_inv = np.linalg.inv(A)  #for calculating inverse of A
result = np.dot(A, A_inv)
identity  = np.eye(A.shape[0]) # identity matrix with same size as A
print("A.A^-1 is :\n",result)
print("\n I is :\n",identity)
print("A * A^-1 = I : ",np.allclose(result, identity))


# 2. Prove AB ̸= BA.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n AB is :\n",AB)
print("\n BA is :\n",BA)
print("\nAB = BA :\n ",np.allclose(AB, BA))

# 3. Prove (AB)^T = B^T A^T.
AB_transpose = np.transpose(AB)
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
B_transpose_A_transpose = np.dot(B_transpose, A_transpose)
print("\n AB^T is :\n",AB_transpose)
print("\n B^T A^T is :\n",B_transpose_A_transpose)
print("\n AB^T = B^T A^T : ",np.allclose(AB_transpose, B_transpose_A_transpose))


# 4. Solve the following system of Linear equation using Inverse Methods.

# Coefficient matrix (A) and constant matrix (B)
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("\nSolution for the system of equations:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])




A.A^-1 is :
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 I is :
 [[1. 0.]
 [0. 1.]]
A * A^-1 = I :  True

 AB is :
 [[23 13]
 [51 29]]

 BA is :
 [[36 44]
 [13 16]]

AB = BA :
  False

 AB^T is :
 [[23 51]
 [13 29]]

 B^T A^T is :
 [[23 51]
 [13 29]]

 AB^T = B^T A^T :  True

Solution for the system of equations:
x = 2.0
y = 1.0
z = -2.0
